### ISSUE TITLE
Set initiative of NPC to same as PC

### ISSUE THREAD

**Issue by dkniffin** [MeAndUnique/FriendZone#2]
Hello! I am loving this FG extension! It makes it a MUCH better experience for PCs to control things like familiars, pets, etc. I'm even using it for spells that have tokens that PCs can move around, such as dancing lights or spiritual weapon. Dancing lights is really neat because I can put lighting effects on the token.

One thing that's a bit annoying though: can you have the NPC's initiative set to the same as the PCs? That way they show up next to each other in the combat tracker. I end up doing this manually at the start of every combat, which can get annoying if there's quite a few cohort NPCs

**Comment by dopeghoti** [comment]
I'll go one further and suggest the possibility of adding a "Spell Effects" category to go along with "Vehicles" as interesting implementations of this idea.  Using this extension for Dancing Lights is _inspired_.

**Comment by MeAndUnique** [comment]
Sorry for the radio silence on this! It appears to have slipped past my radar with how busy I've been as of late.

For the main request, check out my Temporal Fixation extension, which satisfies that use case and a handful more beside.

Did the spell effect category request, whole I agree that is an extremely clever way to use Friend Zone, from a development perspective it is a feature that I would rather give full consideration as it's own extension.

**Comment by dopeghoti** [comment]
> Did the spell effect category request

In the interest of clarification, does that mean we can see this implemented as a stopgap in an upcoming release of _Friend Zone_ while we await what for lack of another name I shall call _Spelling Be_'s release?

**Comment by MeAndUnique** [comment]
I would consider the current capabilities of Friend Zone to qualify as a stop gap, so I don't plan on doing anything more direct with spell effect tokens here.

**Comment by dkniffin** [comment]
re: Temporal Fixation, I'll check that out

re: spell tokens, I've done something very similar, making a token that can move around the map and have lights attached. The problem with putting that into Cohorts, is that it gives the player vision from that token, which shouldn't be true for spell tokens. I agree that a separate section for that would be worthwhile, and everything in that section is controllable by the player, but they don't get vision from them. No idea how hard that would be to implement though 😅
